name: langchain-opensearch-project

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2
    platform: linux/arm64
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_SECURITY_PLUGIN=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Dima1203@
      - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom -Dcom.sun.jndi.ldap.object.trustURLCodebase=false
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - discovery.type=single-node
      - plugins.security.ssl.transport.enforce_hostname_verification=false
      - plugins.security.allow_unsafe_democertificates=true
      - plugins.security.allow_default_init_securityindex=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/opensearch-node1.yml:/usr/share/opensearch/config/opensearch.yml:z
      - ./config/certs:/usr/share/opensearch/config/certs:z
      - opensearch-data1:/usr/share/opensearch/data
      - type: bind
        source: ./config/internal_users.yml
        target: /usr/share/opensearch/config/opensearch-security/internal_users.yml
        read_only: true
      - type: bind
        source: ./config/templates
        target: /usr/share/opensearch/config/templates
        read_only: true
      - ./config/sqlformat.json:/usr/share/opensearch/config/sqlformat.json:ro
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - langchain-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k -u admin:Dima1203@ https://localhost:9200/_cluster/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  opensearch-node2:
    image: opensearchproject/opensearch:2
    platform: linux/arm64
    container_name: opensearch-node2
    volumes:
      - ./config/opensearch-node2.yml:/usr/share/opensearch/config/opensearch.yml:z
      - ./config/certs:/usr/share/opensearch/config/certs:z
      - opensearch-data2:/usr/share/opensearch/data
      - type: bind
        source: ./config/internal_users.yml
        target: /usr/share/opensearch/config/opensearch-security/internal_users.yml
        read_only: true
      - type: bind
        source: ./config/templates
        target: /usr/share/opensearch/config/templates
        read_only: true
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_SECURITY_PLUGIN=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Dima1203@
      - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom -Dcom.sun.jndi.ldap.object.trustURLCodebase=false
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - langchain-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k -u admin:Dima1203@ https://localhost:9200/_cluster/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch-node1:9200","https://opensearch-node2:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Dima1203@
    networks:
      - langchain-network
    depends_on:
      opensearch-node1:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - langchain-network
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash
    depends_on:
      opensearch-node1:
        condition: service_healthy
      opensearch-node2:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./csv_data:/usr/share/logstash/data
      - ./logs/logstash:/usr/share/logstash/logs
      - /usr/share/locale:/usr/share/locale:ro
    environment:
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Dima1203@
      - LANG=uk_UA.UTF-8
      - LC_ALL=uk_UA.UTF-8
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - langchain-network
    deploy:
      resources:
        limits:
          memory: 5G

  langchain:
    build: .
    container_name: langchain
    ports:
      - "5000:5000"
    environment:
      - LANG=uk_UA.UTF-8
      - LANGUAGE=uk_UA:uk
      - LC_ALL=uk_UA.UTF-8
      - OPENSEARCH_HOST=https://opensearch-node1:9200
      - OPENSEARCH_VERIFY_CERTS=false
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Dima1203@
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
    volumes:
      - ./logs/langchain:/app/logs
    networks:
      - langchain-network
    depends_on:
      opensearch-node1:
        condition: service_healthy
      opensearch-node2:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  langchain-network:
    driver: bridge

volumes:
  opensearch-data1:
  opensearch-data2:
  redis-data: