_meta:
  type: "config"
  config_version: 2
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Internal authentication"
        http_enabled: true
        order: 0
        authentication_backend:
          type: intern
