admin:
  cluster_permissions:
    - '*'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - '*'
  tenant_permissions:
    - tenant_patterns:
        - '*'
      allowed_actions:
        - '*'

reader:
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - read
        - search
