cluster.name: opensearch-cluster
node.name: opensearch-node2
network.host: 0.0.0.0
discovery.type: single-node

plugins.security.disabled: true
plugins.security.ssl.http.enabled: false
plugins.security.ssl.transport.enabled: false
plugins.security.allow_default_init_securityindex: true
plugins.security.restapi.admin.enabled: true
plugins.security.nodes_dn:
  - "CN=node.example.com,OU=SSL,O=Test,L=Test,C=DE"

# Audit settings
plugins.security.audit.type: internal_opensearch
plugins.security.authcz.admin_dn:
  - "CN=node.example.com,OU=SSL,O=Test,L=Test,C=DE"
  - "CN=admin,OU=SSL,O=Test,L=Test,C=DE"