cluster.name: opensearch-cluster
node.name: opensearch-node1
network.host: 0.0.0.0
discovery.type: single-node

plugins.security.disabled: true  # Временно отключаем для отладки
plugins.security.ssl.http.enabled: false
plugins.security.ssl.transport.enabled: false
plugins.security.allow_default_init_securityindex: true
