cluster.name: opensearch-cluster
node.name: opensearch-node1
network.host: 0.0.0.0
discovery.type: single-node

plugins.security.disabled: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enabled: true
plugins.security.allow_default_init_securityindex: true
plugins.query.datasources.encryption.masterkey: "your_master_key_here"
